version: '3.7'

x-logging:
    &json-logging
    driver: json-file
    options:
        max-size: "1m"
        max-file: "3"

services:
    cocorohome:
        build:
            context: ./src
            dockerfile: Dockerfile
            args:
                TZ: 'Asia/Tokyo'
        image: cocorohome
        container_name: cocorohome
        restart: always
        env_file:
            - ./.env
        volumes:
            - ./src/config:/config:ro
            - ./src/work:/work
        logging: *json-logging
